# Start from a core stack version
FROM jupyter/scipy-notebook
# Install from requirements.txt file
COPY requirements.txt /tmp/
RUN cd /home/jovyan/work
RUN git clone https://github.com/gitsduran1986/General_Notebook.git
RUN cd /home/
COPY jupyter_notebook_config.py /etc/jupyter/
RUN pip install --requirement /tmp/requirements.txt && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
RUN jupyter contrib nbextension install --user
RUN jupyter nbextensions_configurator enable --user
RUN jupyter nbextension enable collapsible_headings/main
